Add streaming

diff --git a/honda-japan.yaml b/honda-japan.yaml
--- a/honda-japan.yaml
+++ b/honda-japan.yaml
@@ -3,6 +3,23 @@ permissions:
 env:
   MAX_JOBS: '2'
 jobs:
+
+  stream_logs:
+    steps:
+
+      - name: Sanity Checks
+        run: |
+          source /etc/profile.d/parallelworks.sh
+          source /etc/profile.d/parallelworks-env.sh
+          source /pw/.miniconda3/etc/profile.d/conda.sh
+
+          python3 scripts/get_group_allocation_balance.py ${{ inputs.run_hours_3dcs_group }} ${{ inputs.org_name }}
+          if [ $? -ne 0 ]; then
+              echo "$(date) ERROR: No 3DCS balance is available. Exiting workflow." >&2
+              exit 1
+          fi
+
+
   local_preprocessing:
     steps:
 
